baseurl: /nimes
permalink: pretty
markdown: kramdown
paginate: 5
repo: nimes
github_org: maptime
maptime:
  chapter: MaptimeNîmes
  twitter: #TwitterHandle
  #disqus: YOUR DISQUS USERNAME

gems:
  - jekyll-feed
